version: '3.8'

services:
  epaper-postgres:
    image: postgres:16.3
    container_name: epaper-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: epaper-db
    ports:
      - '5432:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: ROOTNAME
      MINIO_ROOT_PASSWORD: CHANGEME123
      MINIO_ACCESS_KEY: KEY
      MINIO_SECRET_KEY: MYSECRET
      MINIO_DOMAIN: minio
    volumes:
      - ./data/minio:/data
    networks:
      default:
        aliases:
          - locals3.minio
    command: server /data --console-address ":9001"
